<?php

use App\Http\Controllers\ChallengeController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\ProgramController;
use App\Http\Controllers\ProgramParticipantController;
use App\Http\Controllers\UserController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
|
| Here is where you can register API routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "api" middleware group. Make something great!
|
*/

Route::prefix('users')->group(function () {
    Route::get('/generate/{dataQuantity}', [UserController::class, 'storeAutoGeneratedData']);
    Route::get('/fetch', [UserController::class, 'indexAll']);
    Route::get('/{id}', [UserController::class, 'show']);
    Route::put('/{id}', [UserController::class, 'update']);
    Route::delete('/{id}', [UserController::class, 'delete']);
});

Route::prefix('challenges')->group(function () {
    Route::get('generate/{dataQuantity}', [ChallengeController::class, 'storeAutoGeneratedData']);
    Route::get('fetch', [ChallengeController::class, 'indexAll']);
    Route::get('/{id}', [ChallengeController::class, 'show']);
    Route::put('/{id}', [ChallengeController::class, 'update']);
    Route::delete('/{id}', [ChallengeController::class, 'delete']);
});

Route::prefix('companies')->group(function () {
    Route::get('generate/{dataQuantity}', [CompanyController::class, 'storeAutoGeneratedData']);
    Route::get('fetch', [CompanyController::class, 'indexAll']);
    Route::get('/{id}', [CompanyController::class, 'show']);
    Route::put('/{id}', [CompanyController::class, 'update']);
    Route::delete('/{id}', [CompanyController::class, 'delete']);
});

Route::prefix('programs')->group(function () {
    Route::get('generate/{dataQuantity}', [ProgramController::class, 'storeAutoGeneratedData']);
    Route::get('fetch', [ProgramController::class, 'indexAll']);
    Route::get('/{id}', [ProgramController::class, 'show']);
    Route::put('/{id}', [ProgramController::class, 'update']);
    Route::delete('/{id}', [ProgramController::class, 'delete']);
});

Route::prefix('program-participants')->group(function () {
    Route::get('generate/{dataQuantity}', [ProgramParticipantController::class, 'storeAutoGeneratedData']);
    Route::get('fetch', [ProgramParticipantController::class, 'indexAll']);
    Route::get('/{id}', [ProgramParticipantController::class, 'show']);
    Route::put('/{id}', [ProgramParticipantController::class, 'update']);
    Route::delete('/{id}', [ProgramParticipantController::class, 'delete']);
});
