<?php

use App\Http\Controllers\ChallengeController;
use App\Http\Controllers\UserController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
|
| Here is where you can register API routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "api" middleware group. Make something great!
|
*/

Route::get('generate-users/{dataQuantity}', [UserController::class, 'storeAutoGeneratedData']);
Route::get('fetch-all-users', [UserController::class, 'indexAll']);

Route::get('generate-challenges/{dataQuantity}', [ChallengeController::class, 'storeAutoGeneratedData']);
Route::get('fetch-all-challenges', [ChallengeController::class, 'indexAll']);
