<?php

namespace App\Http\Controllers;

use App\Helpers\GptAI;
use App\Models\Challenge;
use Illuminate\Http\JsonResponse;
use Throwable;

class ChallengeController extends Controller
{
    public function storeAutoGeneratedData(string $dataQuantity): JsonResponse
    {
        try {
            $prompt = $this->promptDefinition($dataQuantity, Challenge::all());

            $gpt = new GptAI(base_path('storage/certificates/cacert.pem'));

            $response = $gpt->openAI(getenv("OPEN_API_KEY"), $prompt);

            if ($response['error']) {
                throw new \Exception($response['message']);
            }

            $firstChoice = json_decode($response['response']->choices[0]->message->content, true);

            foreach ($firstChoice as $generatedChallenge) {
                $this->createChallenge($generatedChallenge);
            }

            return response()->json([
                "status" => "SUCCESS",
                "message" => "Datos generados correctamente",
                "data" => $firstChoice
            ]);
        } catch (Throwable $th) {
            return response()->json([
                "status" => "ERROR",
                "message" => $th->getMessage()
            ]);
        }
    }

    private function promptDefinition(string $dataQuantity, $challenges): string
    {
        $prompt = "Genera $dataQuantity conjuntos de datos aleatorios donde cada conjunto debe tener un título de un desafío de una vacante laboral ficticia de ámbito profesional, una descripción de ese desafío, una dificultad del 1 al 10 de ese desafío
        y alguno de los siguientes identificadores de usuarios debe ser asociado a ese desafío:";

        $users = User::all();

        foreach ($users as $user) {
            $prompt .= " - $user->id - ";
        }

        $prompt .= "Los siguientes datos existen actualmente en la base de datos: \n";

        foreach ($challenges as $challenge) {
            $prompt .= " - Titulo: $challenge->title, Descripcion: $challenge->description, Dificultad: $challenge->difficulty, UsuarioId: $challenge->user_id \n";
        }

        $prompt .= "La salida no debe tener nada mas que un JSON que contenga un array de conjuntos de datos, donde cada conjunto de datos esté representado como un objeto con las claves 'titulo', 'descripcion', 'dificultad' y 'usuarioId'.";

        return $prompt;
    }

    private function createChallenge(array $challengeData): void
    {
        $challenge = new Challenge();
        $challenge->title = $challengeData["titulo"];
        $challenge->description = $challengeData["descripcion"];
        $challenge->difficulty = $challengeData["dificultad"];
        $challenge->user_id = $challengeData["usuarioId"];
        $challenge->save();
    }

    public function indexAll(): JsonResponse
    {
        $challenges = Challenge::paginate(10);
        return response()->json($challenges);
    }
}
